services:
    metaer_curl_wrapper.curl_wrapper.default:
        class: 'Metaer\CurlWrapperBundle\CurlWrapper'
        public: true

    Metaer\CurlWrapperBundle\CurlWrapper: "@metaer_curl_wrapper.curl_wrapper.default"
