language: php

jobs:
    include:
        - php: '7.0'
        - php: '7.1'
        - php: '7.2'
        - php: '7.3'

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - phpenv config-rm xdebug.ini

install:
    composer update --prefer-dist --no-progress --no-suggest --ansi;

script:
    - vendor/bin/simple-phpunit
